### ISSUE TITLE
App is crashing while installing

### ISSUE THREAD

**Issue by Yogi09** [luish88/Turn-by-Turn-Navigation-Module-for-Android#1]
Project is looking very cool but I am facing this issue, app is crashing while startup

 java.lang.RuntimeException: Cannot create an instance of class com.dev.mytbt.MapViewController
        at android.arch.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:155)
        at android.arch.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:210)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:134)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:102)
        at com.dev.mytbt.FragNavigation.runChecks(FragNavigation.java:302)
        at com.dev.mytbt.FragNavigation.onResume(FragNavigation.java:144)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3140)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2687)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1640)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1932)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1528)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7530)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:622)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:739)

**Comment by mightymop** [comment]
- simply clone the project
- open it (Android Studio)
- go to file: /app/src/main/java/com.dev.mytbt.MapViewController
- make the class public > insert "public" in front of "class" and save file
- compile project and run on mobile...

**Comment by Srikanth-aakuthota** [comment]
Another error I see, attached image
![image](https://user-images.githubusercontent.com/6263180/113449201-eeb79000-941a-11eb-820e-2bf06b40c5b4.png)

**Comment by luish88** [comment]
Hello. Thank you for your interest in my project.
The map files are probably not in the right folder. If you have any issues, please edit the map folder in your code so it matches the folder you want.
I'm sorry, but I'm too far away from the project to be able to help.
